services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./Backend/db-init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - app-network

  fastapi:
    build:
      context: ./fastapi
    container_name: fastapi
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    volumes:
      - ./fastapi:/app
      - ./Frontend:/app/Frontend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app-network


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network


volumes:
  keycloak_data:

networks:
  app-network:
    driver: bridge
